
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - alpha.rudeboy.io
  resources:
  - pizzaorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alpha.rudeboy.io
  resources:
  - pizzaorders/status
  verbs:
  - get
  - patch
  - update
